// examples/gallery.cpp — generate PNGs for all matplotlib-equivalent plot types
//
// Produces one PNG per plot type in the output directory (default: gallery/volcano/).
// Each PNG is 800x600 with a white background and basic styling.
// The corresponding matplotlib PNGs are generated by scripts/matplotlib_gallery.py.
#include <volcano/backend/Backend.hpp>
#include <volcano/render/Renderer.hpp>
#include <volcano/plot/Plot.hpp>
#include <volcano/plot/Style.hpp>
#include <volcano/plot/Transform.hpp>
#include <volcano/plot/Colormap.hpp>
#include <volcano/plot/DataSeries.hpp>
#include <volcano/encode/ImageEncoder.hpp>

#include <volcano/plot/plots/ScatterPlot.hpp>
#include <volcano/plot/plots/LinePlot.hpp>
#include <volcano/plot/plots/BarPlot.hpp>
#include <volcano/plot/plots/GroupedBarPlot.hpp>
#include <volcano/plot/plots/HistPlot.hpp>
#include <volcano/plot/plots/PiePlot.hpp>
#include <volcano/plot/plots/BoxPlot.hpp>
#include <volcano/plot/plots/ViolinPlot.hpp>
#include <volcano/plot/plots/StackPlot.hpp>
#include <volcano/plot/plots/StemPlot.hpp>
#include <volcano/plot/plots/StepPlot.hpp>
#include <volcano/plot/plots/ErrorbarPlot.hpp>
#include <volcano/plot/plots/FillPlot.hpp>
#include <volcano/plot/plots/FillBetweenPlot.hpp>
#include <volcano/plot/plots/BrokenBarHPlot.hpp>
#include <volcano/plot/plots/HeatmapPlot.hpp>
#include <volcano/plot/plots/Hist2DPlot.hpp>
#include <volcano/plot/plots/HexbinPlot.hpp>
#include <volcano/plot/plots/ContourPlot.hpp>
#include <volcano/plot/plots/KDEPlot.hpp>
#include <volcano/plot/plots/ECDFPlot.hpp>
#include <volcano/plot/plots/SurfacePlot.hpp>
#include <volcano/plot/plots/WireframePlot.hpp>
#include <volcano/plot/plots/Scatter3D.hpp>
#include <volcano/plot/plots/Plot3D.hpp>
#include <volcano/plot/plots/Bar3D.hpp>
#include <volcano/plot/plots/Axes3DPlot.hpp>
#include <volcano/plot/plots/MexicanHatPlot.hpp>
#include <volcano/plot/plots/ChirpPlot.hpp>
#include <volcano/plot/plots/QuiverPlot.hpp>
#include <volcano/plot/plots/StreamPlot.hpp>
#include <volcano/plot/plots/PcolormeshPlot.hpp>
#include <volcano/plot/plots/TrisurfPlot.hpp>
#include <volcano/plot/plots/TriContourPlot.hpp>
#include <volcano/plot/plots/SpecgramPlot.hpp>
#include <volcano/plot/plots/ReferenceLines.hpp>
#include <volcano/plot/plots/TripcolorPlot.hpp>
#include <volcano/plot/plots/TriplotPlot.hpp>
#include <volcano/plot/plots/BarbsPlot.hpp>
#include <volcano/plot/plots/SpyPlot.hpp>
#include <volcano/plot/plots/MatshowPlot.hpp>
#include <volcano/plot/plots/PsdPlot.hpp>
#include <volcano/plot/plots/CsdPlot.hpp>
#include <volcano/plot/plots/CoherePlot.hpp>
#include <volcano/plot/plots/XCorrPlot.hpp>
#include <volcano/plot/plots/SpectrumPlot.hpp>
#include <volcano/plot/plots/BarLabelPlot.hpp>
#include <volcano/plot/plots/FigImagePlot.hpp>
#include <volcano/plot/plots/Contour3D.hpp>
#include <volcano/plot/plots/Quiver3D.hpp>
#include <volcano/plot/plots/Errorbar3D.hpp>
#include <volcano/plot/plots/VoxelsPlot.hpp>

#include <cmath>
#include <iostream>
#include <random>
#include <string>
#include <string_view>
#include <vector>
#include <filesystem>

using namespace volcano;
using namespace volcano::plot;

namespace {

constexpr uint32_t kWidth = 1600;
constexpr uint32_t kHeight = 1200;

struct GalleryCtx {
    backend::BackendDesc desc;
    std::unique_ptr<backend::IBackend> backend;
    std::unique_ptr<render::Renderer> renderer;
    std::string outDir;

    explicit GalleryCtx(std::string dir) : outDir(std::move(dir)) {
        desc.width = kWidth;
        desc.height = kHeight;
        desc.samples = vk::SampleCountFlagBits::e4;
        backend = backend::createHeadlessBackend(desc);
        renderer = std::make_unique<render::Renderer>(*backend);
        std::filesystem::create_directories(outDir);
    }

    void render(Figure& fig, std::string_view name) {
        renderer->prepare(fig);
        renderer->renderFrame(fig);
        auto px = backend->readbackRgba8();
        auto enc = encode::createCpuEncoder(encode::ImageFormat::Png);
        std::string path = outDir + "/" + std::string(name) + ".png";
        if (enc->encodeToFile(px, desc.width, desc.height, path)) {
            std::cout << "  wrote " << path << "\n";
        } else {
            std::cerr << "  FAILED " << path << "\n";
        }
    }
};

FigureStyle galleryStyle() {
    // matplotlib default style: white bg, black spines, no grid.
    // dpi=200 with 1600x1200 px keeps the 8x6in figure size (2x DPI).
    auto s = styles::defaultStyle();
    s.dpi = 200.0f;
    return s;
}

Axes* setupAxes(Figure& fig, std::string_view title,
                const char* xlabel = "X", const char* ylabel = "Y") {
    auto* ax = fig.addAxes();
    ax->setStyle(galleryStyle());
    ax->setTitle(std::string(title));
    ax->style().xAxis.visible = true;
    ax->style().yAxis.visible = true;
    ax->style().xAxis.label = xlabel;
    ax->style().yAxis.label = ylabel;
    return ax;
}

// ── Data generators ───────────────────────────────────────────────────────

// Deterministic RNG shared with scripts/matplotlib_gallery.py — a uint64
// LCG feeding Irwin-Hall gaussians (sum of 12 uniforms - 6). Bit-identical
// on both sides so the gallery renders the same datasets.
struct SharedRng {
    uint64_t state = 42;
    double uniform() {
        state = state * 6364136223846793005ULL + 1442695040888963407ULL;
        return double(state >> 11) * (1.0 / 9007199254740992.0);
    }
    double gauss() {
        double s = 0.0;
        for (int i = 0; i < 12; ++i) s += uniform();
        return s - 6.0;
    }
};
SharedRng& sRng() {
    static SharedRng r;
    return r;
}

std::vector<float> linspace(float a, float b, int n) {
    std::vector<float> v(n);
    for (int i = 0; i < n; ++i)
        v[i] = a + (b - a) * float(i) / float(n - 1);
    return v;
}

// ── Plot generators ───────────────────────────────────────────────────────

void plotScatter(GalleryCtx& ctx) {
    Figure fig(1, 1);
    auto* ax = setupAxes(fig, "Scatter");
    ax->style().xAxis.label = "X";
    ax->style().yAxis.label = "Y";
    Series2D s;
    s.color = Color::fromRgba8(31, 119, 180);
    s.marker = MarkerStyle::Circle;
    // mpl s=25 pt² → marker diameter = 2·sqrt(25/π)·(dpi/72) ≈ 15.7 px.
    s.size = 15.7f;
    s.label = "data";
    // Same draw order as mpl: x=randn(200), then y=randn(200).
    std::vector<float> sx(200), sy(200);
    for (auto& v : sx) v = float(sRng().gauss());
    for (auto& v : sy) v = float(sRng().gauss());
    for (int i = 0; i < 200; ++i)
        s.points.push_back({sx[i], sy[i]});
    ax->addPlot(std::make_unique<ScatterPlot>(std::move(s)));
    ax->style().legend.visible = true;
    ctx.render(fig, "scatter");
}

void plotLine(GalleryCtx& ctx) {
    Figure fig(1, 1);
    auto* ax = setupAxes(fig, "Line");
    ax->style().xAxis.label = "X";
    ax->style().yAxis.label = "Y";
    Series2D s;
    s.color = Color::fromRgba8(31, 119, 180);
    s.lineWidth = 2.0f;
    s.label = "sin(x)";
    auto x = linspace(0, 10, 200);
    for (float xi : x)
        s.points.push_back({xi, std::sin(xi)});
    ax->addPlot(std::make_unique<LinePlot>(std::move(s)));
    ax->style().legend.visible = true;
    ctx.render(fig, "line");
}

void plotBar(GalleryCtx& ctx) {
    Figure fig(1, 1);
    auto* ax = setupAxes(fig, "Bar");
    ax->style().xAxis.label = "Category";
    ax->style().yAxis.label = "Value";
    BarData bd;
    bd.heights = {3, 7, 5, 8, 4, 6, 5};
    bd.labels = {"A", "B", "C", "D", "E", "F", "G"};
    bd.width = 0.8f;
    ax->addPlot(std::make_unique<BarPlot>(std::move(bd)));
    ctx.render(fig, "bar");
}

void plotGroupedBar(GalleryCtx& ctx) {
    Figure fig(1, 1);
    auto* ax = setupAxes(fig, "Grouped Bar");
    ax->style().xAxis.label = "Category";
    ax->style().yAxis.label = "Value";
    GroupedBarConfig cfg;
    cfg.barWidth = 0.75f;  // mpl: ax.bar(x + (i-1)*w, s, w) with w=0.25
    cfg.groupLabels = {"A", "B", "C", "D"};
    cfg.seriesLabels = {"Series 1", "Series 2", "Series 3"};
    std::vector<std::vector<float>> heights = {
        {3, 5, 2, 4},
        {5, 3, 6, 2},
        {2, 4, 3, 5},
    };
    ax->addPlot(std::make_unique<GroupedBarPlot>(std::move(heights), cfg));
    ax->style().legend.visible = true;
    // mpl: ax.set_xticks(x) + xticklabels at group centers (i+0.5 here).
    ax->style().xAxis.ticks.positions = {0.5f, 1.5f, 2.5f, 3.5f};
    ax->style().xAxis.ticks.labels = {"A", "B", "C", "D"};
    ctx.render(fig, "grouped_bar");
}

void plotHist(GalleryCtx& ctx) {
    Figure fig(1, 1);
    auto* ax = setupAxes(fig, "Histogram");
    ax->style().xAxis.label = "Value";
    ax->style().yAxis.label = "Count";
    std::vector<float> samples;
    for (int i = 0; i < 1000; ++i)
        samples.push_back(float(sRng().gauss()));
    HistConfig cfg;
    cfg.binCount = 30;
    ax->addPlot(std::make_unique<HistPlot>(std::move(samples), cfg));
    ctx.render(fig, "hist");
}

void plotPie(GalleryCtx& ctx) {
    Figure fig(1, 1);
    auto* ax = fig.addAxes();
    ax->setStyle(galleryStyle());
    ax->setTitle("Pie");
    // Pie charts don't show axes/spines/ticks/grid.
    ax->style().xAxis.visible = false;
    ax->style().yAxis.visible = false;
    ax->style().xAxis.grid = false;
    ax->style().yAxis.grid = false;
    PieData pd;
    pd.values = {30, 20, 25, 15, 10};
    pd.labels = {"A", "B", "C", "D", "E"};
    // matplotlib default color cycle: tab10
    pd.colors = {
        Color::fromRgba8(31, 119, 180),   // blue
        Color::fromRgba8(255, 127, 14),   // orange
        Color::fromRgba8(44, 160, 44),    // green
        Color::fromRgba8(214, 39, 40),    // red
        Color::fromRgba8(148, 103, 189),  // purple
    };
    ax->addPlot(std::make_unique<PiePlot>(std::move(pd)));
    ctx.render(fig, "pie");
}

void plotBox(GalleryCtx& ctx) {
    Figure fig(1, 1);
    auto* ax = setupAxes(fig, "Box Plot");
    ax->style().xAxis.label = "Group";
    ax->style().yAxis.label = "Value";
    std::vector<std::vector<float>> groups;
    for (int g = 0; g < 4; ++g) {
        std::vector<float> group;
        for (int i = 0; i < 100; ++i)
            group.push_back(float(sRng().gauss() * (1.0 + g * 0.2) + g));
        groups.push_back(std::move(group));
    }
    BoxPlotConfig cfg;
    cfg.labels = {"G1", "G2", "G3", "G4"};
    cfg.fillBox = false;  // mpl boxplot default: patch_artist=False
    ax->addPlot(std::make_unique<BoxPlot>(std::move(groups), cfg));
    ax->setXCategories({"G1", "G2", "G3", "G4"});  // mpl labels=
    ctx.render(fig, "box");
}

void plotViolin(GalleryCtx& ctx) {
    Figure fig(1, 1);
    auto* ax = setupAxes(fig, "Violin Plot");
    ax->style().xAxis.label = "Group";
    ax->style().yAxis.label = "Value";
    std::vector<std::vector<float>> groups;
    for (int g = 0; g < 4; ++g) {
        std::vector<float> group;
        for (int i = 0; i < 150; ++i)
            group.push_back(float(sRng().gauss() + g * 0.5));
        groups.push_back(std::move(group));
    }
    ViolinConfig cfg;
    cfg.labels = {"G1", "G2", "G3", "G4"};
    // Set categorical X-axis tick labels at violin centers (x=1,2,3,4).
    ax->style().xAxis.ticks.positions = {1.0f, 2.0f, 3.0f, 4.0f};
    ax->style().xAxis.ticks.labels = {"G1", "G2", "G3", "G4"};
    ax->addPlot(std::make_unique<ViolinPlot>(std::move(groups), cfg));
    ctx.render(fig, "violin");
}

void plotStack(GalleryCtx& ctx) {
    Figure fig(1, 1);
    auto* ax = setupAxes(fig, "Stack Plot");
    ax->style().xAxis.label = "X";
    ax->style().yAxis.label = "Y";
    auto x = linspace(0, 10, 50);
    std::vector<std::vector<float>> ys;
    for (int s = 0; s < 3; ++s) {
        std::vector<float> y;
        for (float xi : x)
            y.push_back(std::sin(xi + s) * 2 + 3);
        ys.push_back(std::move(y));
    }
    std::vector<Color> colors = {
        Color::fromRgba8(31, 119, 180),
        Color::fromRgba8(255, 127, 14),
        Color::fromRgba8(44, 160, 44),
    };
    std::vector<std::string> labels = {"A", "B", "C"};
    ax->addPlot(std::make_unique<StackPlot>(x, std::move(ys), colors, labels));
    ax->style().legend.visible = true;
    ctx.render(fig, "stack");
}

void plotStem(GalleryCtx& ctx) {
    Figure fig(1, 1);
    auto* ax = setupAxes(fig, "Stem Plot");
    ax->style().xAxis.label = "X";
    ax->style().yAxis.label = "Y";
    std::vector<float> x, y;
    for (int i = 0; i < 20; ++i) {
        x.push_back(float(i));
        y.push_back(std::sin(float(i) * 0.5f));
    }
    StemConfig scfg;
    scfg.markerSize = 16.7f;  // mpl markersize=6pt → 16.7 px at 200 dpi
    ax->addPlot(std::make_unique<StemPlot>(x, y, scfg));
    ctx.render(fig, "stem");
}

void plotStep(GalleryCtx& ctx) {
    Figure fig(1, 1);
    auto* ax = setupAxes(fig, "Step Plot");
    ax->style().xAxis.label = "X";
    ax->style().yAxis.label = "Y";
    auto x = linspace(0, 10, 30);
    std::vector<float> y;
    for (float xi : x)
        y.push_back(std::exp(-xi * 0.2f));
    ax->addPlot(std::make_unique<StepPlot>(x, y));
    ctx.render(fig, "step");
}

void plotErrorbar(GalleryCtx& ctx) {
    Figure fig(1, 1);
    auto* ax = setupAxes(fig, "Errorbar");
    ax->style().xAxis.label = "X";
    ax->style().yAxis.label = "Y";
    auto x = linspace(0, 10, 15);
    std::vector<float> y, yerr;
    for (float xi : x) {
        y.push_back(std::sin(xi) * 2);
        yerr.push_back(0.3f);
    }
    ErrorbarConfig cfg;
    cfg.yerr = yerr;
    cfg.markerSize = 16.7f;  // mpl markersize=6pt → 16.7 px at 200 dpi
    cfg.capSize = 8.3f;      // mpl capsize=3pt → 8.3 px at 200 dpi
    cfg.drawCaps = true;
    cfg.drawLine = false;    // mpl fmt="o" draws markers only
    ax->addPlot(std::make_unique<ErrorbarPlot>(x, y, cfg));
    ctx.render(fig, "errorbar");
}

void plotFill(GalleryCtx& ctx) {
    Figure fig(1, 1);
    auto* ax = setupAxes(fig, "Fill");
    ax->style().xAxis.label = "X";
    ax->style().yAxis.label = "Y";
    Series2D s;
    s.color = Color::fromRgba8(31, 119, 180, 128);
    auto x = linspace(0, 10, 100);
    for (float xi : x)
        s.points.push_back({xi, std::sin(xi) * std::exp(-xi * 0.1f)});
    ax->addPlot(std::make_unique<FillPlot>(std::move(s)));
    ctx.render(fig, "fill");
}

void plotFillBetween(GalleryCtx& ctx) {
    Figure fig(1, 1);
    auto* ax = setupAxes(fig, "Fill Between");
    ax->style().xAxis.label = "X";
    ax->style().yAxis.label = "Y";
    auto x = linspace(0, 10, 100);
    std::vector<float> y1, y2;
    for (float xi : x) {
        y1.push_back(std::sin(xi) + 1);
        y2.push_back(std::sin(xi) - 1);
    }
    ax->addPlot(std::make_unique<FillBetweenPlot>(x, y1, y2,
        Color::fromRgba8(31, 119, 180, 80)));
    ctx.render(fig, "fill_between");
}

void plotBrokenBarH(GalleryCtx& ctx) {
    Figure fig(1, 1);
    auto* ax = setupAxes(fig, "Broken Bar Horizontal");
    ax->style().xAxis.label = "X";
    ax->style().yAxis.label = "Y";
    std::vector<BarHSegment> segs = {
        {0, 5, 0, 1},
        {7, 3, 0, 1},
        {2, 4, 2, 1},
        {8, 2, 2, 1},
    };
    BrokenBarHConfig cfg;
    // mpl: row y∈[0,1] → #1f77b4, row y∈[2,3] → #2ca02c (opaque).
    cfg.colors = {
        Color::fromRgba8(31, 119, 180), Color::fromRgba8(31, 119, 180),
        Color::fromRgba8(44, 160, 44), Color::fromRgba8(44, 160, 44),
    };
    ax->addPlot(std::make_unique<BrokenBarHPlot>(std::move(segs), cfg));
    ctx.render(fig, "broken_barh");
}

void plotHeatmap(GalleryCtx& ctx) {
    Figure fig(1, 1);
    auto* ax = setupAxes(fig, "Heatmap", "", "");
    Grid2D grid;
    grid.width = 30;
    grid.height = 20;
    grid.xRange = {0, 10};
    grid.yRange = {0, 10};
    grid.origin = "lower";  // mpl: imshow(..., origin="lower")
    grid.values.resize(30 * 20);
    for (uint32_t j = 0; j < 20; ++j)
        for (uint32_t i = 0; i < 30; ++i) {
            float x = float(i) / 29 * 10;
            float y = float(j) / 19 * 10;
            grid.values[j * 30 + i] = std::sin(x * 0.5f) * std::cos(y * 0.5f);
        }
    ax->addPlot(std::make_unique<HeatmapPlot>(std::move(grid)));
    ax->style().colorbar.visible = true;
    ax->style().colorbar.colormap = "viridis";
    ctx.render(fig, "heatmap");
}

void plotHist2D(GalleryCtx& ctx) {
    Figure fig(1, 1);
    auto* ax = setupAxes(fig, "2D Histogram", "", "");
    // Same draw order as mpl: x=randn(5000)*2, then y=randn(5000)*2.
    std::vector<float> x(5000), y(5000);
    for (auto& v : x) v = float(sRng().gauss() * 2);
    for (auto& v : y) v = float(sRng().gauss() * 2);
    Hist2DConfig cfg;
    cfg.bins = Hist2DBinMethod::Fixed;  // mpl: bins=[40, 30]
    cfg.nBinsX = 40;
    cfg.nBinsY = 30;
    ax->addPlot(std::make_unique<Hist2DPlot>(x, y, cfg));
    ax->style().colorbar.visible = true;
    ctx.render(fig, "hist2d");
}

void plotHexbin(GalleryCtx& ctx) {
    Figure fig(1, 1);
    auto* ax = setupAxes(fig, "Hexbin", "", "");
    std::vector<float> x(3000), y(3000);
    for (auto& v : x) v = float(sRng().gauss() * 2);
    for (auto& v : y) v = float(sRng().gauss() * 2);
    HexbinConfig cfg;
    cfg.gridsize = 25;
    ax->addPlot(std::make_unique<HexbinPlot>(x, y, cfg));
    ax->style().colorbar.visible = true;
    ctx.render(fig, "hexbin");
}

void plotContour(GalleryCtx& ctx) {
    Figure fig(1, 1);
    auto* ax = setupAxes(fig, "Contour");
    Grid2D grid;
    grid.width = 50;
    grid.height = 50;
    grid.xRange = {-3, 3};
    grid.yRange = {-3, 3};
    grid.values.resize(50 * 50);
    for (uint32_t j = 0; j < 50; ++j)
        for (uint32_t i = 0; i < 50; ++i) {
            float x = -3 + float(i) / 49 * 6;
            float y = -3 + float(j) / 49 * 6;
            grid.values[j * 50 + i] = std::sin(x) * std::cos(y);
        }
    ContourConfig cfg;
    ax->addPlot(std::make_unique<ContourPlot>(std::move(grid), cfg));
    ctx.render(fig, "contour");
}

void plotContourf(GalleryCtx& ctx) {
    Figure fig(1, 1);
    auto* ax = setupAxes(fig, "Filled Contour");
    Grid2D grid;
    grid.width = 50;
    grid.height = 50;
    grid.xRange = {-3, 3};
    grid.yRange = {-3, 3};
    grid.values.resize(50 * 50);
    for (uint32_t j = 0; j < 50; ++j)
        for (uint32_t i = 0; i < 50; ++i) {
            float x = -3 + float(i) / 49 * 6;
            float y = -3 + float(j) / 49 * 6;
            grid.values[j * 50 + i] = -(x*x + y*y);
        }
    ContourConfig cfg;
    cfg.cmap = &colormaps::viridis();
    cfg.numLevels = 20;  // mpl: ax.contourf(..., levels=20, cmap="viridis")
    ax->addPlot(std::make_unique<ContourfPlot>(std::move(grid), cfg));
    ax->style().colorbar.visible = true;
    ctx.render(fig, "contourf");
}

void plotKDE(GalleryCtx& ctx) {
    Figure fig(1, 1);
    auto* ax = setupAxes(fig, "KDE", "", "");
    std::vector<Point2D> samples(500);
    for (auto& s : samples) s.x = float(sRng().gauss());
    for (auto& s : samples) s.y = float(sRng().gauss());
    // mpl: gaussian_kde evaluated on np.mgrid[-4:4:100j, -4:4:100j].
    auto kde = std::make_unique<KDEPlot>(std::move(samples), 100, 100);
    kde->evalRange({-4, 4}, {-4, 4});
    ax->addPlot(std::move(kde));
    ax->setXlim(-4, 4);
    ax->setYlim(-4, 4);
    ax->style().colorbar.visible = true;
    ctx.render(fig, "kde");
}

void plotECDF(GalleryCtx& ctx) {
    Figure fig(1, 1);
    auto* ax = setupAxes(fig, "ECDF");
    ax->style().xAxis.label = "Value";
    ax->style().yAxis.label = "CDF";
    std::vector<float> samples;
    for (int i = 0; i < 500; ++i)
        samples.push_back(float(sRng().gauss()));
    std::ranges::sort(samples);
    ECDFConfig cfg;
    cfg.fill = true;
    ax->addPlot(std::make_unique<ECDFPlot>(std::move(samples), cfg));
    ctx.render(fig, "ecdf");
}


/// mpl mplot3d: draw the pane/box/tick-label frame behind the 3D artists.
static void addAxes3D(Axes* ax, const Camera3D& cam) {
    Viewport v;
    v.x = {cam.dataMin.x, cam.dataMax.x};
    v.y = {cam.dataMin.y, cam.dataMax.y};
    v.z = {cam.dataMin.z, cam.dataMax.z};
    ax->addPlot(std::make_unique<Axes3DPlot>(cam, v));
}

void plotSurface(GalleryCtx& ctx) {
    Figure fig(1, 1);
    auto* ax = setupAxes(fig, "3D Surface", "", "");
    Grid2D grid;
    grid.width = 40;
    grid.height = 40;
    grid.xRange = {-5, 5};
    grid.yRange = {-5, 5};
    grid.values.resize(40 * 40);
    for (uint32_t j = 0; j < 40; ++j)
        for (uint32_t i = 0; i < 40; ++i) {
            float x = -5 + float(i) / 39 * 10;
            float y = -5 + float(j) / 39 * 10;
            grid.values[j * 40 + i] = std::sin(x * 0.5f) * std::cos(y * 0.5f);
        }
    Camera3D cam{{3.3f, -5.78f, 3.85f}, {0, 0, 0}, {0, 0, 1}}; // mpl elev=30 azim=-60
    cam.dataMin = {-5, -5, -1}; cam.dataMax = {5, 5, 1};
    cam.aspect = float(kWidth) / float(kHeight);
    addAxes3D(ax, cam);
    auto p = std::make_unique<SurfacePlot>(std::move(grid), cam);
    ax->addPlot(std::move(p));
    ctx.render(fig, "surface");
}

void plotWireframe(GalleryCtx& ctx) {
    Figure fig(1, 1);
    auto* ax = setupAxes(fig, "3D Wireframe", "", "");
    Grid2D grid;
    grid.width = 20;
    grid.height = 20;
    grid.xRange = {-5, 5};
    grid.yRange = {-5, 5};
    grid.values.resize(20 * 20);
    for (uint32_t j = 0; j < 20; ++j)
        for (uint32_t i = 0; i < 20; ++i) {
            float x = -5 + float(i) / 19 * 10;
            float y = -5 + float(j) / 19 * 10;
            grid.values[j * 20 + i] = std::sin(x * 0.5f) * std::cos(y * 0.5f);
        }
    Camera3D cam{{3.3f, -5.78f, 3.85f}, {0, 0, 0}, {0, 0, 1}}; // mpl elev=30 azim=-60
    cam.dataMin = {-5, -5, -1}; cam.dataMax = {5, 5, 1};
    cam.aspect = float(kWidth) / float(kHeight);
    addAxes3D(ax, cam);
    WireframeConfig cfg;
    auto p = std::make_unique<WireframePlot>(std::move(grid), cfg);
    p->setCamera(cam);
    ax->addPlot(std::move(p));
    ctx.render(fig, "wireframe");
}

void plotScatter3D(GalleryCtx& ctx) {
    Figure fig(1, 1);
    auto* ax = setupAxes(fig, "3D Scatter", "", "");
    std::vector<float> x(100), y(100), z(100);
    for (auto& v : x) v = float(sRng().gauss() * 3);
    for (auto& v : y) v = float(sRng().gauss() * 3);
    for (auto& v : z) v = float(sRng().gauss() * 3);
    Camera3D cam{{3.3f, -5.78f, 3.85f}, {0, 0, 0}, {0, 0, 1}}; // mpl elev=30 azim=-60
    cam.dataMin = {-9, -9, -9}; cam.dataMax = {9, 9, 9};
    cam.aspect = float(kWidth) / float(kHeight);
    addAxes3D(ax, cam);
    Scatter3DConfig cfg;
    cfg.size = 15.7f;  // mpl s=25 pt² → ~15.7 px diameter at 200 dpi
    auto p = std::make_unique<Scatter3D>(x, y, z, cfg);
    p->setCamera(cam);
    ax->addPlot(std::move(p));
    ctx.render(fig, "scatter3d");
}

void plotPlot3D(GalleryCtx& ctx) {
    Figure fig(1, 1);
    auto* ax = setupAxes(fig, "3D Line", "", "");
    std::vector<float> x, y, z;
    for (int i = 0; i < 200; ++i) {
        float t = float(i) / 199 * 4 * M_PI;
        x.push_back(std::cos(t) * 3);
        y.push_back(std::sin(t) * 3);
        z.push_back(t * 0.5f);
    }
    Camera3D cam{{3.3f, -5.78f, 3.85f}, {0, 0, 0}, {0, 0, 1}}; // mpl elev=30 azim=-60
    cam.dataMin = {-3, -3, 0}; cam.dataMax = {3, 3, 6.3f};
    cam.aspect = float(kWidth) / float(kHeight);
    addAxes3D(ax, cam);
    Plot3DConfig cfg;
    auto p = std::make_unique<Plot3D>(x, y, z, cfg);
    p->setCamera(cam);
    ax->addPlot(std::move(p));
    ctx.render(fig, "plot3d");
}

void plotBar3D(GalleryCtx& ctx) {
    Figure fig(1, 1);
    auto* ax = setupAxes(fig, "3D Bar", "", "");
    std::vector<float> bx, by, bz, dx, dy, dz;
    for (int i = 0; i < 4; ++i)
        for (int j = 0; j < 4; ++j) {
            bx.push_back(float(i));
            by.push_back(float(j));
            bz.push_back(0);
            dx.push_back(0.7f);
            dy.push_back(0.7f);
            dz.push_back(float(i + j + 1));
        }
    Camera3D cam{{3.3f, -5.78f, 3.85f}, {0, 0, 0}, {0, 0, 1}}; // mpl elev=30 azim=-60
    cam.dataMin = {-0.3f, -0.3f, 0}; cam.dataMax = {3.7f, 3.7f, 7};
    cam.aspect = float(kWidth) / float(kHeight);
    addAxes3D(ax, cam);
    auto p = std::make_unique<Bar3D>(bx, by, bz, dx, dy, dz);
    p->setCamera(cam);
    ax->addPlot(std::move(p));
    ctx.render(fig, "bar3d");
}

void plotMexicanHat(GalleryCtx& ctx) {
    Figure fig(1, 1);
    auto* ax = setupAxes(fig, "Mexican Hat Wavelet", "", "");
    Camera3D cam{{3.3f, -5.78f, 3.85f}, {0, 0, 0}, {0, 0, 1}}; // mpl elev=30 azim=-60
    cam.dataMin = {-5, -5, -0.5f}; cam.dataMax = {5, 5, 2};
    cam.aspect = float(kWidth) / float(kHeight);
    addAxes3D(ax, cam);
    MexicanHatConfig cfg;
    auto p = std::make_unique<MexicanHatPlot>(1.0f, Range{-5, 5}, Range{-5, 5}, 40, 40, cfg);
    p->setCamera(cam);
    ax->addPlot(std::move(p));
    ctx.render(fig, "mexican_hat");
}

void plotChirp(GalleryCtx& ctx) {
    Figure fig(1, 1);
    auto* ax = setupAxes(fig, "Chirp Signal");
    ax->style().xAxis.label = "Time";
    ax->style().yAxis.label = "Amplitude";
    ChirpPlotConfig cfg;
    cfg.color = Color::fromRgba8(31, 119, 180);
    cfg.lineWidth = 1.5f;
    ax->addPlot(std::make_unique<ChirpPlot>(1.0, 50.0, 1.0, Range{0, 1}, 2000, cfg));
    ctx.render(fig, "chirp");
}

// ── Extended coverage ─────────────────────────────────────────────────────

void plotQuiver(GalleryCtx& ctx) {
    Figure fig(1, 1);
    auto* ax = setupAxes(fig, "Quiver", "X", "Y");
    std::vector<float> x, y, u, v;
    for (int j = 0; j < 15; ++j)
        for (int i = 0; i < 15; ++i) {
            float px = -2.0f + i * (4.0f / 14), py = -2.0f + j * (4.0f / 14);
            x.push_back(px); y.push_back(py);
            u.push_back(-py); v.push_back(px);
        }
    ax->addPlot(std::make_unique<QuiverPlot>(std::move(x), std::move(y),
                                           std::move(u), std::move(v)));
    ax->setXlim(-2.5, 2.5); ax->setYlim(-2.5, 2.5);
    ctx.render(fig, "quiver");
}

void plotStreamplot(GalleryCtx& ctx) {
    Figure fig(1, 1);
    auto* ax = setupAxes(fig, "Streamplot", "X", "Y");
    Grid2D gu, gv;
    gu.width = gu.height = gv.width = gv.height = 30;
    gu.xRange = gv.xRange = {-2, 2};
    gu.yRange = gv.yRange = {-2, 2};
    gu.values.resize(900); gv.values.resize(900);
    for (int j = 0; j < 30; ++j)
        for (int i = 0; i < 30; ++i) {
            float px = -2.0f + i * (4.0f / 29), py = -2.0f + j * (4.0f / 29);
            gu.values[j * 30 + i] = -py;
            gv.values[j * 30 + i] = px;
        }
    StreamConfig sc;
    sc.color = Color::fromRgba8(31, 119, 180);   // mpl default C0
    ax->addPlot(std::make_unique<StreamPlot>(std::move(gu), std::move(gv),
                                             sc));
    ax->setXlim(-2, 2); ax->setYlim(-2, 2);
    ctx.render(fig, "streamplot");
}

void plotImshow(GalleryCtx& ctx) {
    Figure fig(1, 1);
    auto* ax = setupAxes(fig, "imshow", "X", "Y");
    Grid2D g;
    g.width = g.height = 24;
    g.xRange = {-3, 3}; g.yRange = {-3, 3};
    g.values.resize(24 * 24);
    for (uint32_t j = 0; j < 24; ++j)
        for (uint32_t i = 0; i < 24; ++i) {
            float x = -3 + float(i) / 23 * 6, y = -3 + float(j) / 23 * 6;
            g.values[j * 24 + i] = std::sin(x) * std::cos(y) +
                                   std::exp(-(x * x + y * y));
        }
    ax->imshow(std::move(g), colormaps::viridis(), "nearest", "auto");
    ax->setXlim(-3, 3); ax->setYlim(-3, 3);
    ax->style().colorbar.visible = true;
    ctx.render(fig, "imshow");
}

void plotPcolormesh(GalleryCtx& ctx) {
    Figure fig(1, 1);
    auto* ax = setupAxes(fig, "pcolormesh", "X", "Y");
    const int n = 25;
    std::vector<float> x(n + 1), y(n + 1), C(n * n);
    for (int i = 0; i <= n; ++i) x[i] = -3 + i * 6.0f / n;
    for (int j = 0; j <= n; ++j) y[j] = -3 + j * 6.0f / n;
    for (int j = 0; j < n; ++j)
        for (int i = 0; i < n; ++i) {
            float cx = (x[i] + x[i + 1]) * 0.5f, cy = (y[j] + y[j + 1]) * 0.5f;
            C[j * n + i] = std::sin(cx) * std::cos(cy);
        }
    PcolormeshConfig cfg;
    ax->addPlot(std::make_unique<PcolormeshPlot>(std::move(x), std::move(y),
                                               std::move(C), n, n, cfg));
    ax->setXlim(-3, 3); ax->setYlim(-3, 3);
    ax->style().colorbar.visible = true;
    ctx.render(fig, "pcolormesh");
}

void plotTricontourf(GalleryCtx& ctx) {
    Figure fig(1, 1);
    auto* ax = setupAxes(fig, "tricontourf", "X", "Y");
    std::vector<float> x, y, z;
    for (int i = 0; i < 300; ++i) {
        float px = float(sRng().uniform()) * 6 - 3;
        float py = float(sRng().uniform()) * 6 - 3;
        x.push_back(px); y.push_back(py);
        z.push_back(std::sin(px) * std::cos(py));
    }
    TriContourConfig cfg;
    cfg.numLevels = 12;
    ax->addPlot(std::make_unique<TriContourfPlot>(std::move(x), std::move(y),
                                                std::move(z), cfg));
    ax->setXlim(-3, 3); ax->setYlim(-3, 3);
    ax->style().colorbar.visible = true;
    ctx.render(fig, "tricontourf");
}

void plotPolar(GalleryCtx& ctx) {
    Figure fig(1, 1);
    auto* ax = setupAxes(fig, "Polar");
    ax->setProjection("polar");
    Series2D s;
    s.color = Color::fromRgba8(31, 119, 180);
    s.lineWidth = 2.0f;
    for (int i = 0; i <= 200; ++i) {
        float th = float(i) / 200 * 2.0f * float(M_PI) * 3.0f;
        s.points.push_back({th, th / (2.0f * float(M_PI) * 3.0f)});
    }
    ax->addPlot(std::make_unique<LinePlot>(std::move(s)));
    ax->setViewport({0.0f, 6.2832f * 3.0f, 0.0f, 1.0f, 0, 1});
    ctx.render(fig, "polar");
}

void plotEventplot(GalleryCtx& ctx) {
    Figure fig(1, 1);
    auto* ax = setupAxes(fig, "Eventplot", "Time", "Trial");
    std::vector<std::vector<float>> rows(6);
    for (int r = 0; r < 6; ++r)
        for (int i = 0; i < 20; ++i)
            rows[r].push_back(float(sRng().uniform()) * 10.0f);
    ax->eventplot(rows);
    ax->setXlim(0, 10);
    ctx.render(fig, "eventplot");
}

void plotTable(GalleryCtx& ctx) {
    Figure fig(1, 1);
    auto* ax = setupAxes(fig, "Table");
    Series2D s2;
    for (float x : linspace(0, 10, 60))
        s2.points.push_back({x, std::sin(x)});
    ax->addPlot(std::make_unique<LinePlot>(std::move(s2)));
    ax->table({{"Metric", "Mean", "Std"},
               {"A", "0.5", "0.1"}, {"B", "1.2", "0.3"}}, "bottom");
    ctx.render(fig, "table");
}

void plotSpecgram(GalleryCtx& ctx) {
    Figure fig(1, 1);
    auto* ax = setupAxes(fig, "Specgram", "Time", "Frequency");
    std::vector<float> sig(4096);
    for (int i = 0; i < 4096; ++i) {
        float t = float(i) / 4096;
        sig[i] = std::sin(2 * float(M_PI) * (10 + 40 * t) * t * 8);
    }
    SpecgramConfig cfg;
    ax->addPlot(std::make_unique<SpecgramPlot>(std::move(sig), cfg));
    ctx.render(fig, "specgram");
}

void plotTrisurf(GalleryCtx& ctx) {
    Figure fig(1, 1);
    auto* ax = setupAxes(fig, "Trisurf");
    std::vector<float> x, y, z;
    for (int i = 0; i < 200; ++i) {
        float a = float(sRng().uniform()) * 2 * float(M_PI);
        float r = float(sRng().uniform()) * 2;
        x.push_back(r * std::cos(a)); y.push_back(r * std::sin(a));
        z.push_back(std::sin(x.back()) * std::cos(y.back()));
    }
    auto cam = Camera3D::viewInit(30.0f, -60.0f);
    cam.aspect = float(kWidth) / float(kHeight);
    cam.dataMin = {-2, -2, -1}; cam.dataMax = {2, 2, 1};
    Viewport v; v.x = {-2, 2}; v.y = {-2, 2}; v.z = {-1, 1};
    ax->addPlot(std::make_unique<Axes3DPlot>(cam, v));
    auto p = std::make_unique<TrisurfPlot>(std::move(x), std::move(y),
                                           std::move(z));
    p->setCamera(cam);
    ax->addPlot(std::move(p));
    ctx.render(fig, "trisurf");
}

// ── Remaining mpl plot types ──────────────────────────────────────────────

void plotStairs(GalleryCtx& ctx) {
    Figure fig(1, 1);
    auto* ax = setupAxes(fig, "Stairs");
    ax->style().xAxis.label = "Bin";
    ax->style().yAxis.label = "Count";
    // mpl: ax.stairs(hist_values, edges)
    std::vector<float> values = {4, 9, 15, 22, 18, 11, 6, 3};
    std::vector<float> edges  = {0, 1, 2, 3, 4, 5, 6, 7, 8};
    ax->addPlot(std::make_unique<StairsPlot>(
        std::move(values), std::move(edges),
        Color::fromRgba8(31, 119, 180), 1.5f));
    ctx.render(fig, "stairs");
}

void plotTripcolor(GalleryCtx& ctx) {
    Figure fig(1, 1);
    auto* ax = setupAxes(fig, "tripcolor", "X", "Y");
    std::vector<float> x, y, z;
    for (int i = 0; i < 300; ++i) {
        float px = float(sRng().uniform()) * 6 - 3;
        float py = float(sRng().uniform()) * 6 - 3;
        x.push_back(px); y.push_back(py);
        z.push_back(std::sin(px) * std::cos(py));
    }
    TripcolorConfig cfg;
    cfg.cmap = &colormaps::viridis();
    ax->addPlot(std::make_unique<TripcolorPlot>(std::move(x), std::move(y),
                                              std::move(z), cfg));
    ax->setXlim(-3, 3); ax->setYlim(-3, 3);
    ax->style().colorbar.visible = true;
    ctx.render(fig, "tripcolor");
}

void plotTriplot(GalleryCtx& ctx) {
    Figure fig(1, 1);
    auto* ax = setupAxes(fig, "triplot", "X", "Y");
    std::vector<float> x, y;
    for (int i = 0; i < 60; ++i) {
        x.push_back(float(sRng().uniform()) * 6 - 3);
        y.push_back(float(sRng().uniform()) * 6 - 3);
    }
    TriplotConfig cfg;
    cfg.showMarkers = true;   // mpl triplot default marker='o'
    cfg.color = Color::fromRgba8(31, 119, 180);        // mpl prop cycle C0
    cfg.markerColor = Color::fromRgba8(31, 119, 180);
    ax->addPlot(std::make_unique<TriplotPlot>(std::move(x), std::move(y), cfg));
    ax->setXlim(-3, 3); ax->setYlim(-3, 3);
    ctx.render(fig, "triplot");
}

void plotTricontour(GalleryCtx& ctx) {
    Figure fig(1, 1);
    auto* ax = setupAxes(fig, "tricontour", "X", "Y");
    std::vector<float> x, y, z;
    for (int i = 0; i < 300; ++i) {
        float px = float(sRng().uniform()) * 6 - 3;
        float py = float(sRng().uniform()) * 6 - 3;
        x.push_back(px); y.push_back(py);
        z.push_back(std::sin(px) * std::cos(py));
    }
    TriContourConfig cfg;
    cfg.numLevels = 12;
    cfg.cmap = &colormaps::viridis();  // mpl default: level-colored lines
    ax->addPlot(std::make_unique<TriContourPlot>(std::move(x), std::move(y),
                                               std::move(z), cfg));
    ax->setXlim(-3, 3); ax->setYlim(-3, 3);
    ctx.render(fig, "tricontour");
}

void plotBarbs(GalleryCtx& ctx) {
    Figure fig(1, 1);
    auto* ax = setupAxes(fig, "barbs", "X", "Y");
    std::vector<float> x, y, u, v;
    for (int j = 0; j < 8; ++j)
        for (int i = 0; i < 8; ++i) {
            float px = i * 0.5f, py = j * 0.5f;
            x.push_back(px); y.push_back(py);
            // Smooth wind field with a range of speeds (knots).
            u.push_back(20.0f * std::sin(px * 0.8f) + 15.0f);
            v.push_back(20.0f * std::cos(py * 0.8f));
        }
    ax->addPlot(std::make_unique<BarbsPlot>(std::move(x), std::move(y),
                                          std::move(u), std::move(v)));
    ctx.render(fig, "barbs");
}

void plotSpy(GalleryCtx& ctx) {
    Figure fig(1, 1);
    auto* ax = setupAxes(fig, "spy", "", "");
    const uint32_t n = 24;
    std::vector<float> m(n * n, 0.0f);
    for (uint32_t i = 0; i < n; ++i) {
        m[i * n + i] = 1.0f;                       // diagonal
        if (i + 3 < n) m[i * n + i + 3] = 1.0f;    // off-diagonal band
        if (i >= 3)  m[i * n + i - 3] = 1.0f;
    }
    m[2 * n + 18] = 1.0f; m[20 * n + 5] = 1.0f;    // a few outliers
    SpyConfig cfg; cfg.color = Color::black();     // mpl spy default
    ax->addPlot(std::make_unique<SpyPlot>(std::move(m), n, n, cfg));
    ctx.render(fig, "spy");
}

void plotMatshow(GalleryCtx& ctx) {
    Figure fig(1, 1);
    auto* ax = setupAxes(fig, "matshow", "", "");
    const uint32_t n = 12;
    std::vector<float> m(n * n);
    for (uint32_t j = 0; j < n; ++j)
        for (uint32_t i = 0; i < n; ++i)
            m[j * n + i] = std::sin(float(i) * 0.5f) * std::cos(float(j) * 0.5f);
    MatshowConfig cfg;
    cfg.cmap = &colormaps::viridis();
    ax->addPlot(std::make_unique<MatshowPlot>(std::move(m), n, n, cfg));
    ctx.render(fig, "matshow");
}

/// Shared deterministic signal: sin(2π·10·t) + sin(2π·40·t) + 0.4·noise,
/// Fs=1024, 1024 samples. Mirrored bit-for-bit on the mpl side (same LCG).
static std::vector<float> gallerySignal() {
    std::vector<float> s(1024);
    for (int i = 0; i < 1024; ++i) {
        float t = float(i) / 1024.0f;
        s[i] = std::sin(2 * float(M_PI) * 10 * t)
             + std::sin(2 * float(M_PI) * 40 * t)
             + 0.4f * float(sRng().uniform() * 2 - 1);
    }
    return s;
}

void plotPsd(GalleryCtx& ctx) {
    Figure fig(1, 1);
    auto* ax = setupAxes(fig, "psd", "Frequency",
                         "Power Spectral Density (dB/Hz)");
    ax->style().xAxis.grid = true; ax->style().yAxis.grid = true;
    PsdConfig cfg; cfg.sampleRate = 1024.0f; cfg.nfft = 256;
    ax->addPlot(std::make_unique<PsdPlot>(gallerySignal(), cfg));
    ctx.render(fig, "psd");
}

void plotCsd(GalleryCtx& ctx) {
    Figure fig(1, 1);
    auto* ax = setupAxes(fig, "csd", "Frequency",
                         "Cross Spectrum Magnitude (dB)");
    ax->style().xAxis.grid = true; ax->style().yAxis.grid = true;
    auto s1 = gallerySignal();
    auto s2 = gallerySignal();
    CsdConfig cfg; cfg.sampleRate = 1024.0f; cfg.nfft = 256;
    ax->addPlot(std::make_unique<CsdPlot>(std::move(s1), std::move(s2), cfg));
    ctx.render(fig, "csd");
}

void plotCohere(GalleryCtx& ctx) {
    Figure fig(1, 1);
    auto* ax = setupAxes(fig, "cohere", "Frequency", "Coherence");
    ax->style().xAxis.grid = true; ax->style().yAxis.grid = true;
    auto s1 = gallerySignal();
    auto s2 = gallerySignal();
    CohereConfig cfg; cfg.sampleRate = 1024.0f; cfg.nfft = 256;
    ax->addPlot(std::make_unique<CoherePlot>(std::move(s1), std::move(s2), cfg));
    ctx.render(fig, "cohere");
}

void plotXcorr(GalleryCtx& ctx) {
    Figure fig(1, 1);
    auto* ax = setupAxes(fig, "xcorr", "Lag", "Correlation");
    ax->style().xAxis.grid = true; ax->style().yAxis.grid = true;
    auto s1 = gallerySignal();
    auto s2 = gallerySignal();
    XCorrConfig cfg; cfg.maxLags = 50;
    ax->addPlot(std::make_unique<XCorrPlot>(std::move(s1), std::move(s2), cfg));
    ctx.render(fig, "xcorr");
}

void plotSpectrum(GalleryCtx& ctx, SpectrumType type,
                  SpectrumScale scale, std::string_view name,
                  std::string_view ylabel) {
    Figure fig(1, 1);
    auto* ax = setupAxes(fig, name, "Frequency", std::string(ylabel).c_str());
    SpectrumConfig cfg;
    cfg.type = type; cfg.scale = scale; cfg.sampleRate = 1024.0f;
    ax->addPlot(std::make_unique<SpectrumPlot>(gallerySignal(), cfg));
    ctx.render(fig, name);
}

void plotReflines(GalleryCtx& ctx) {
    Figure fig(1, 1);
    auto* ax = setupAxes(fig, "Reference lines");
    Series2D s;
    s.color = Color::fromRgba8(31, 119, 180);
    s.lineWidth = 1.5f;
    for (float x : linspace(0, 10, 100))
        s.points.push_back({x, std::sin(x)});
    ax->addPlot(std::make_unique<LinePlot>(std::move(s)));
    ax->axhline(0.0f, Color::fromRgba8(214, 39, 40), 1.0f);     // mpl C3 red
    ax->axvline(5.0f, Color::fromRgba8(44, 160, 44), 1.0f);     // C2 green
    ax->axhspan(0.5f, 1.0f, Color::fromRgba8(255, 215, 0, 60));
    ax->axvspan(7.0f, 9.0f, Color::fromRgba8(148, 103, 189, 60));
    ax->axline({0.0f, 0.8f}, -0.15f, Color::fromRgba8(140, 86, 75), 1.0f);
    ctx.render(fig, "reflines");
}

void plotHlinesVlines(GalleryCtx& ctx) {
    Figure fig(1, 1);
    auto* ax = setupAxes(fig, "hlines / vlines");
    ax->hlines({0.5f, 1.0f, 1.5f}, 0.0f, 4.0f,
               Color::fromRgba8(31, 119, 180), 1.5f);
    ax->vlines({1.0f, 2.0f, 3.0f}, 0.0f, 2.0f,
               Color::fromRgba8(255, 127, 14), 1.5f);
    ax->setXlim(0, 4); ax->setYlim(0, 2);
    ctx.render(fig, "hlines_vlines");
}

void plotAnnotate(GalleryCtx& ctx) {
    Figure fig(1, 1);
    auto* ax = setupAxes(fig, "annotate");
    Series2D s;
    s.color = Color::fromRgba8(31, 119, 180);
    s.lineWidth = 1.5f;
    for (float x : linspace(0, 10, 200))
        s.points.push_back({x, std::sin(x)});
    ax->addPlot(std::make_unique<LinePlot>(std::move(s)));
    // mpl: ax.annotate('local max', xy=(pi/2, 1), xytext=(3, 1.5),
    //                  arrowprops=dict(facecolor='black', shrink=0.05))
    auto* a = ax->annotate(float(M_PI_2), 1.0f, 3.0f, 1.5f, "local max");
    a->arrowColor = Color::black();
    ax->text(6.0f, -1.0f, "local min");
    ax->setXlim(0, 10); ax->setYlim(-1.5, 2.0f);
    ctx.render(fig, "annotate");
}

void plotBarLabel(GalleryCtx& ctx) {
    Figure fig(1, 1);
    auto* ax = setupAxes(fig, "bar_label");
    ax->style().xAxis.label = "Category";
    ax->style().yAxis.label = "Value";
    BarData bd;
    bd.heights = {3, 7, 5, 8, 4};
    bd.labels = {"A", "B", "C", "D", "E"};
    bd.width = 0.8f;
    std::vector<float> bx, bh;
    for (size_t i = 0; i < bd.heights.size(); ++i) {
        bx.push_back(float(i));
        bh.push_back(bd.heights[i]);
    }
    ax->addPlot(std::make_unique<BarPlot>(std::move(bd)));
    // mpl ax.bar_label(container): value labels at the bar edge.
    ax->addPlot(std::make_unique<BarLabelPlot>(std::move(bx), std::move(bh),
                                             0.0f));
    ax->setXCategories({"A", "B", "C", "D", "E"});  // mpl tick_label
    ctx.render(fig, "bar_label");
}

void plotFigimage(GalleryCtx& ctx) {
    Figure fig(1, 1);
    auto* ax = setupAxes(fig, "figimage");
    Series2D s;
    s.color = Color::fromRgba8(31, 119, 180);
    for (float x : linspace(0, 10, 100))
        s.points.push_back({x, std::sin(x)});
    ax->addPlot(std::make_unique<LinePlot>(std::move(s)));
    // mpl fig.figimage(X): RGBA pixel patch in figure space.
    const uint32_t w = 64, h = 64;
    std::vector<uint32_t> px(w * h);
    for (uint32_t j = 0; j < h; ++j)
        for (uint32_t i = 0; i < w; ++i) {
            uint32_t r = 255 * i / (w - 1), g = 255 * j / (h - 1);
            // 0xAABBGGRR: R in bits 0-7, G in 8-15, B in 16-23.
            px[j * w + i] = (128u << 24) | (128u << 16) | (g << 8) | r;
        }
    // mpl figimage(xo, yo): pixels from figure bottom-left; our y is the
    // top edge in Y-down figure pixels.
    FigImageConfig cfg; cfg.x = 120; cfg.y = kHeight - 120 - h;
    ax->addPlot(std::make_unique<FigImagePlot>(std::move(px), w, h, cfg));
    ctx.render(fig, "figimage");
}

void plotContour3D(GalleryCtx& ctx) {
    Figure fig(1, 1);
    auto* ax = setupAxes(fig, "contour3d", "", "");
    Grid2D grid;
    grid.width = 40; grid.height = 40;
    grid.xRange = {-5, 5}; grid.yRange = {-5, 5};
    grid.values.resize(40 * 40);
    for (uint32_t j = 0; j < 40; ++j)
        for (uint32_t i = 0; i < 40; ++i) {
            float x = -5 + float(i) / 39 * 10, y = -5 + float(j) / 39 * 10;
            grid.values[j * 40 + i] = std::sin(x * 0.5f) * std::cos(y * 0.5f);
        }
    auto cam = Camera3D::viewInit(30.0f, -60.0f);
    cam.aspect = float(kWidth) / float(kHeight);
    cam.dataMin = {-5, -5, -1}; cam.dataMax = {5, 5, 1};
    addAxes3D(ax, cam);
    Contour3DConfig cfg;
    cfg.cmap = &colormaps::viridis();
    cfg.zLevel = -1.0f; cfg.zOffset = false;
    auto p = std::make_unique<Contour3D>(std::move(grid), cfg);
    p->setCamera(cam);
    ax->addPlot(std::move(p));
    ctx.render(fig, "contour3d");
}

void plotQuiver3D(GalleryCtx& ctx) {
    Figure fig(1, 1);
    auto* ax = setupAxes(fig, "quiver3d", "", "");
    std::vector<float> x, y, z, u, v, w;
    const int n = 5;
    for (int k = 0; k < n; ++k)
        for (int j = 0; j < n; ++j)
            for (int i = 0; i < n; ++i) {
                float px = i * 0.5f - 1.0f, py = j * 0.5f - 1.0f,
                      pz = k * 0.5f - 1.0f;
                x.push_back(px); y.push_back(py); z.push_back(pz);
                u.push_back(-py); v.push_back(px); w.push_back(0.4f);
            }
    auto cam = Camera3D::viewInit(30.0f, -60.0f);
    cam.aspect = float(kWidth) / float(kHeight);
    cam.dataMin = {-1, -1, -1}; cam.dataMax = {1, 1, 1};
    addAxes3D(ax, cam);
    Quiver3DConfig cfg;
    cfg.color = Color::fromRgba8(31, 119, 180);
    auto p = std::make_unique<Quiver3D>(std::move(x), std::move(y), std::move(z),
                                        std::move(u), std::move(v), std::move(w),
                                        cfg);
    p->setCamera(cam);
    ax->addPlot(std::move(p));
    ctx.render(fig, "quiver3d");
}

void plotErrorbar3D(GalleryCtx& ctx) {
    Figure fig(1, 1);
    auto* ax = setupAxes(fig, "errorbar3d", "", "");
    std::vector<float> x, y, z, ze;
    for (int i = 0; i < 8; ++i) {
        x.push_back(float(i));
        y.push_back(std::sin(float(i)));
        z.push_back(float(i) * 0.5f);
        ze.push_back(0.2f + 0.1f * float(i % 3));
    }
    auto cam = Camera3D::viewInit(30.0f, -60.0f);
    cam.aspect = float(kWidth) / float(kHeight);
    cam.dataMin = {0, -1.5f, 0}; cam.dataMax = {7, 1.5f, 4};
    addAxes3D(ax, cam);
    Errorbar3DConfig cfg;
    cfg.zerr = ze;
    cfg.markerSize = 16.7f;  // mpl markersize=6pt → 16.7 px at 200 dpi
    cfg.capSize = 13.9f;     // mpl capsize=5pt → 13.9 px at 200 dpi
    auto p = std::make_unique<Errorbar3D>(std::move(x), std::move(y),
                                          std::move(z), cfg);
    p->setCamera(cam);
    ax->addPlot(std::move(p));
    ctx.render(fig, "errorbar3d");
}

void plotVoxels(GalleryCtx& ctx) {
    Figure fig(1, 1);
    auto* ax = setupAxes(fig, "voxels", "", "");
    const uint32_t n = 6;
    std::vector<uint8_t> filled(n * n * n, 0);
    for (uint32_t k = 0; k < n; ++k)
        for (uint32_t j = 0; j < n; ++j)
            for (uint32_t i = 0; i < n; ++i) {
                // Sphere-ish solid: fill where (i-c)^2+(j-c)^2+(k-c)^2 < r^2
                float c = (n - 1) * 0.5f;
                float di = float(i) - c, dj = float(j) - c, dk = float(k) - c;
                if (di * di + dj * dj + dk * dk < 7.0f)
                    filled[k * n * n + j * n + i] = 1;
            }
    auto cam = Camera3D::viewInit(30.0f, -60.0f);
    cam.aspect = float(kWidth) / float(kHeight);
    cam.dataMin = {0, 0, 0}; cam.dataMax = {float(n), float(n), float(n)};
    addAxes3D(ax, cam);
    auto p = std::make_unique<VoxelsPlot>(std::move(filled), n, n, n);
    p->setCamera(cam);
    ax->addPlot(std::move(p));
    ctx.render(fig, "voxels");
}

} // namespace

int main(int argc, char** argv) {
    std::string outDir = "gallery/volcano";
    if (argc > 1) outDir = argv[1];

    std::cout << "Generating VolcanoPlot gallery in " << outDir << "/\n";
    GalleryCtx ctx(outDir);

    // 2D plots
    plotScatter(ctx);
    plotLine(ctx);
    plotBar(ctx);
    plotGroupedBar(ctx);
    plotHist(ctx);
    plotPie(ctx);
    plotBox(ctx);
    plotViolin(ctx);
    plotStack(ctx);
    plotStem(ctx);
    plotStep(ctx);
    plotErrorbar(ctx);
    plotFill(ctx);
    plotFillBetween(ctx);
    plotBrokenBarH(ctx);
    plotHeatmap(ctx);
    plotHist2D(ctx);
    plotHexbin(ctx);
    plotContour(ctx);
    plotContourf(ctx);
    plotKDE(ctx);
    plotECDF(ctx);

    // 3D plots
    plotSurface(ctx);
    plotWireframe(ctx);
    plotScatter3D(ctx);
    plotPlot3D(ctx);
    plotBar3D(ctx);
    plotMexicanHat(ctx);
    plotChirp(ctx);

    // Extended coverage
    plotQuiver(ctx);
    plotStreamplot(ctx);
    plotImshow(ctx);
    plotPcolormesh(ctx);
    plotTricontourf(ctx);
    plotPolar(ctx);
    plotEventplot(ctx);
    plotTable(ctx);
    plotSpecgram(ctx);
    plotTrisurf(ctx);

    // Remaining mpl plot types
    plotStairs(ctx);
    plotTripcolor(ctx);
    plotTriplot(ctx);
    plotTricontour(ctx);
    plotBarbs(ctx);
    plotSpy(ctx);
    plotMatshow(ctx);
    plotPsd(ctx);
    plotCsd(ctx);
    plotCohere(ctx);
    plotXcorr(ctx);
    plotSpectrum(ctx, SpectrumType::Magnitude, SpectrumScale::dB,
                 "magnitude_spectrum", "Magnitude (dB)");
    plotSpectrum(ctx, SpectrumType::Phase, SpectrumScale::Linear,
                 "phase_spectrum", "Phase (rad)");
    plotSpectrum(ctx, SpectrumType::Angle, SpectrumScale::Linear,
                 "angle_spectrum", "Angle (rad)");
    plotReflines(ctx);
    plotHlinesVlines(ctx);
    plotAnnotate(ctx);
    plotBarLabel(ctx);
    plotFigimage(ctx);
    plotContour3D(ctx);
    plotQuiver3D(ctx);
    plotErrorbar3D(ctx);
    plotVoxels(ctx);

    std::cout << "Done. Generated " << 62 << " plots.\n";
    return 0;
}
