// examples/gallery.cpp — generate PNGs for all matplotlib-equivalent plot types
//
// Produces one PNG per plot type in the output directory (default: gallery/volcano/).
// Each PNG is 800x600 with a white background and basic styling.
// The corresponding matplotlib PNGs are generated by scripts/matplotlib_gallery.py.
#include <volcano/backend/Backend.hpp>
#include <volcano/render/Renderer.hpp>
#include <volcano/plot/Plot.hpp>
#include <volcano/plot/Style.hpp>
#include <volcano/plot/Transform.hpp>
#include <volcano/plot/Colormap.hpp>
#include <volcano/plot/DataSeries.hpp>
#include <volcano/encode/ImageEncoder.hpp>

#include <volcano/plot/plots/ScatterPlot.hpp>
#include <volcano/plot/plots/LinePlot.hpp>
#include <volcano/plot/plots/BarPlot.hpp>
#include <volcano/plot/plots/GroupedBarPlot.hpp>
#include <volcano/plot/plots/HistPlot.hpp>
#include <volcano/plot/plots/PiePlot.hpp>
#include <volcano/plot/plots/BoxPlot.hpp>
#include <volcano/plot/plots/ViolinPlot.hpp>
#include <volcano/plot/plots/StackPlot.hpp>
#include <volcano/plot/plots/StemPlot.hpp>
#include <volcano/plot/plots/StepPlot.hpp>
#include <volcano/plot/plots/ErrorbarPlot.hpp>
#include <volcano/plot/plots/FillPlot.hpp>
#include <volcano/plot/plots/FillBetweenPlot.hpp>
#include <volcano/plot/plots/BrokenBarHPlot.hpp>
#include <volcano/plot/plots/HeatmapPlot.hpp>
#include <volcano/plot/plots/Hist2DPlot.hpp>
#include <volcano/plot/plots/HexbinPlot.hpp>
#include <volcano/plot/plots/ContourPlot.hpp>
#include <volcano/plot/plots/KDEPlot.hpp>
#include <volcano/plot/plots/ECDFPlot.hpp>
#include <volcano/plot/plots/SurfacePlot.hpp>
#include <volcano/plot/plots/WireframePlot.hpp>
#include <volcano/plot/plots/Scatter3D.hpp>
#include <volcano/plot/plots/Plot3D.hpp>
#include <volcano/plot/plots/Bar3D.hpp>
#include <volcano/plot/plots/MexicanHatPlot.hpp>
#include <volcano/plot/plots/ChirpPlot.hpp>

#include <cmath>
#include <iostream>
#include <random>
#include <string>
#include <string_view>
#include <vector>
#include <filesystem>

using namespace volcano;
using namespace volcano::plot;

namespace {

constexpr uint32_t kWidth = 800;
constexpr uint32_t kHeight = 600;

struct GalleryCtx {
    backend::BackendDesc desc;
    std::unique_ptr<backend::IBackend> backend;
    std::unique_ptr<render::Renderer> renderer;
    std::string outDir;

    explicit GalleryCtx(std::string dir) : outDir(std::move(dir)) {
        desc.width = kWidth;
        desc.height = kHeight;
        desc.samples = vk::SampleCountFlagBits::e4;
        backend = backend::createHeadlessBackend(desc);
        renderer = std::make_unique<render::Renderer>(*backend);
        std::filesystem::create_directories(outDir);
    }

    void render(Figure& fig, std::string_view name) {
        renderer->prepare(fig);
        renderer->renderFrame(fig);
        auto px = backend->readbackRgba8();
        auto enc = encode::createCpuEncoder(encode::ImageFormat::Png);
        std::string path = outDir + "/" + std::string(name) + ".png";
        if (enc->encodeToFile(px, desc.width, desc.height, path)) {
            std::cout << "  wrote " << path << "\n";
        } else {
            std::cerr << "  FAILED " << path << "\n";
        }
    }
};

FigureStyle galleryStyle() {
    FigureStyle s = styles::seabornStyle();
    s.faceColor = Color::white();
    return s;
}

Axes* setupAxes(Figure& fig, std::string_view title) {
    auto* ax = fig.addAxes();
    ax->setStyle(galleryStyle());
    ax->setTitle(std::string(title));
    ax->style().xAxis.visible = true;
    ax->style().yAxis.visible = true;
    ax->style().xAxis.label = "X";
    ax->style().yAxis.label = "Y";
    return ax;
}

// ── Data generators ───────────────────────────────────────────────────────

std::mt19937& rng() {
    static std::mt19937 r(42);
    return r;
}

std::vector<float> linspace(float a, float b, int n) {
    std::vector<float> v(n);
    for (int i = 0; i < n; ++i)
        v[i] = a + (b - a) * float(i) / float(n - 1);
    return v;
}

// ── Plot generators ───────────────────────────────────────────────────────

void plotScatter(GalleryCtx& ctx) {
    Figure fig(1, 1);
    auto* ax = setupAxes(fig, "Scatter");
    ax->style().xAxis.label = "X";
    ax->style().yAxis.label = "Y";
    Series2D s;
    s.color = Color::fromRgba8(31, 119, 180);
    s.marker = MarkerStyle::Circle;
    s.size = 5.0f;
    s.label = "data";
    std::normal_distribution<float> d(0, 1);
    for (int i = 0; i < 200; ++i)
        s.points.push_back({d(rng()), d(rng())});
    ax->addPlot(std::make_unique<ScatterPlot>(std::move(s)));
    ax->style().legend.visible = true;
    ctx.render(fig, "scatter");
}

void plotLine(GalleryCtx& ctx) {
    Figure fig(1, 1);
    auto* ax = setupAxes(fig, "Line");
    ax->style().xAxis.label = "X";
    ax->style().yAxis.label = "Y";
    Series2D s;
    s.color = Color::fromRgba8(31, 119, 180);
    s.lineWidth = 2.0f;
    s.label = "sin(x)";
    auto x = linspace(0, 10, 200);
    for (float xi : x)
        s.points.push_back({xi, std::sin(xi)});
    ax->addPlot(std::make_unique<LinePlot>(std::move(s)));
    ax->style().legend.visible = true;
    ctx.render(fig, "line");
}

void plotBar(GalleryCtx& ctx) {
    Figure fig(1, 1);
    auto* ax = setupAxes(fig, "Bar");
    ax->style().xAxis.label = "Category";
    ax->style().yAxis.label = "Value";
    BarData bd;
    bd.heights = {3, 7, 5, 8, 4, 6, 5};
    bd.labels = {"A", "B", "C", "D", "E", "F", "G"};
    bd.width = 0.8f;
    ax->addPlot(std::make_unique<BarPlot>(std::move(bd)));
    ctx.render(fig, "bar");
}

void plotGroupedBar(GalleryCtx& ctx) {
    Figure fig(1, 1);
    auto* ax = setupAxes(fig, "Grouped Bar");
    ax->style().xAxis.label = "Category";
    ax->style().yAxis.label = "Value";
    GroupedBarConfig cfg;
    cfg.groupLabels = {"A", "B", "C", "D"};
    cfg.seriesLabels = {"Series 1", "Series 2", "Series 3"};
    std::vector<std::vector<float>> heights = {
        {3, 5, 2, 4},
        {5, 3, 6, 2},
        {2, 4, 3, 5},
    };
    ax->addPlot(std::make_unique<GroupedBarPlot>(std::move(heights), cfg));
    ax->style().legend.visible = true;
    ctx.render(fig, "grouped_bar");
}

void plotHist(GalleryCtx& ctx) {
    Figure fig(1, 1);
    auto* ax = setupAxes(fig, "Histogram");
    ax->style().xAxis.label = "Value";
    ax->style().yAxis.label = "Count";
    std::normal_distribution<float> d(0, 1);
    std::vector<float> samples;
    for (int i = 0; i < 1000; ++i)
        samples.push_back(d(rng()));
    HistConfig cfg;
    cfg.binCount = 30;
    ax->addPlot(std::make_unique<HistPlot>(std::move(samples), cfg));
    ctx.render(fig, "hist");
}

void plotPie(GalleryCtx& ctx) {
    Figure fig(1, 1);
    auto* ax = fig.addAxes();
    ax->setStyle(galleryStyle());
    ax->setTitle("Pie");
    // Pie charts don't show axes/spines/ticks/grid.
    ax->style().xAxis.visible = false;
    ax->style().yAxis.visible = false;
    ax->style().xAxis.grid = false;
    ax->style().yAxis.grid = false;
    PieData pd;
    pd.values = {30, 20, 25, 15, 10};
    pd.labels = {"A", "B", "C", "D", "E"};
    // matplotlib default color cycle: tab10
    pd.colors = {
        Color::fromRgba8(31, 119, 180),   // blue
        Color::fromRgba8(255, 127, 14),   // orange
        Color::fromRgba8(44, 160, 44),    // green
        Color::fromRgba8(214, 39, 40),    // red
        Color::fromRgba8(148, 103, 189),  // purple
    };
    ax->addPlot(std::make_unique<PiePlot>(std::move(pd)));
    ctx.render(fig, "pie");
}

void plotBox(GalleryCtx& ctx) {
    Figure fig(1, 1);
    auto* ax = setupAxes(fig, "Box Plot");
    ax->style().xAxis.label = "Group";
    ax->style().yAxis.label = "Value";
    std::normal_distribution<float> d(0, 1);
    std::vector<std::vector<float>> groups;
    for (int g = 0; g < 4; ++g) {
        std::vector<float> group;
        std::normal_distribution<float> gd(g, 1.0f + g * 0.2f);
        for (int i = 0; i < 100; ++i)
            group.push_back(gd(rng()));
        groups.push_back(std::move(group));
    }
    BoxPlotConfig cfg;
    cfg.labels = {"G1", "G2", "G3", "G4"};
    ax->addPlot(std::make_unique<BoxPlot>(std::move(groups), cfg));
    ctx.render(fig, "box");
}

void plotViolin(GalleryCtx& ctx) {
    Figure fig(1, 1);
    auto* ax = setupAxes(fig, "Violin Plot");
    ax->style().xAxis.label = "Group";
    ax->style().yAxis.label = "Value";
    std::vector<std::vector<float>> groups;
    for (int g = 0; g < 4; ++g) {
        std::vector<float> group;
        std::normal_distribution<float> gd(g * 0.5f, 1.0f);
        for (int i = 0; i < 150; ++i)
            group.push_back(gd(rng()));
        groups.push_back(std::move(group));
    }
    ViolinConfig cfg;
    cfg.labels = {"G1", "G2", "G3", "G4"};
    // Set categorical X-axis tick labels at violin centers (x=1,2,3,4).
    ax->style().xAxis.ticks.positions = {1.0f, 2.0f, 3.0f, 4.0f};
    ax->style().xAxis.ticks.labels = {"G1", "G2", "G3", "G4"};
    ax->addPlot(std::make_unique<ViolinPlot>(std::move(groups), cfg));
    ctx.render(fig, "violin");
}

void plotStack(GalleryCtx& ctx) {
    Figure fig(1, 1);
    auto* ax = setupAxes(fig, "Stack Plot");
    ax->style().xAxis.label = "X";
    ax->style().yAxis.label = "Y";
    auto x = linspace(0, 10, 50);
    std::vector<std::vector<float>> ys;
    for (int s = 0; s < 3; ++s) {
        std::vector<float> y;
        for (float xi : x)
            y.push_back(std::sin(xi + s) * 2 + 3);
        ys.push_back(std::move(y));
    }
    std::vector<Color> colors = {
        Color::fromRgba8(31, 119, 180),
        Color::fromRgba8(255, 127, 14),
        Color::fromRgba8(44, 160, 44),
    };
    std::vector<std::string> labels = {"A", "B", "C"};
    ax->addPlot(std::make_unique<StackPlot>(x, std::move(ys), colors, labels));
    ax->style().legend.visible = true;
    ctx.render(fig, "stack");
}

void plotStem(GalleryCtx& ctx) {
    Figure fig(1, 1);
    auto* ax = setupAxes(fig, "Stem Plot");
    ax->style().xAxis.label = "X";
    ax->style().yAxis.label = "Y";
    std::vector<float> x, y;
    for (int i = 0; i < 20; ++i) {
        x.push_back(float(i));
        y.push_back(std::sin(float(i) * 0.5f));
    }
    ax->addPlot(std::make_unique<StemPlot>(x, y));
    ctx.render(fig, "stem");
}

void plotStep(GalleryCtx& ctx) {
    Figure fig(1, 1);
    auto* ax = setupAxes(fig, "Step Plot");
    ax->style().xAxis.label = "X";
    ax->style().yAxis.label = "Y";
    auto x = linspace(0, 10, 30);
    std::vector<float> y;
    for (float xi : x)
        y.push_back(std::exp(-xi * 0.2f));
    ax->addPlot(std::make_unique<StepPlot>(x, y));
    ctx.render(fig, "step");
}

void plotErrorbar(GalleryCtx& ctx) {
    Figure fig(1, 1);
    auto* ax = setupAxes(fig, "Errorbar");
    ax->style().xAxis.label = "X";
    ax->style().yAxis.label = "Y";
    auto x = linspace(0, 10, 15);
    std::vector<float> y, yerr;
    for (float xi : x) {
        y.push_back(std::sin(xi) * 2);
        yerr.push_back(0.3f);
    }
    ErrorbarConfig cfg;
    cfg.yerr = yerr;
    ax->addPlot(std::make_unique<ErrorbarPlot>(x, y, cfg));
    ctx.render(fig, "errorbar");
}

void plotFill(GalleryCtx& ctx) {
    Figure fig(1, 1);
    auto* ax = setupAxes(fig, "Fill");
    ax->style().xAxis.label = "X";
    ax->style().yAxis.label = "Y";
    Series2D s;
    s.color = Color::fromRgba8(31, 119, 180, 128);
    auto x = linspace(0, 10, 100);
    for (float xi : x)
        s.points.push_back({xi, std::sin(xi) * std::exp(-xi * 0.1f)});
    ax->addPlot(std::make_unique<FillPlot>(std::move(s)));
    ctx.render(fig, "fill");
}

void plotFillBetween(GalleryCtx& ctx) {
    Figure fig(1, 1);
    auto* ax = setupAxes(fig, "Fill Between");
    ax->style().xAxis.label = "X";
    ax->style().yAxis.label = "Y";
    auto x = linspace(0, 10, 100);
    std::vector<float> y1, y2;
    for (float xi : x) {
        y1.push_back(std::sin(xi) + 1);
        y2.push_back(std::sin(xi) - 1);
    }
    ax->addPlot(std::make_unique<FillBetweenPlot>(x, y1, y2,
        Color::fromRgba8(31, 119, 180, 80)));
    ctx.render(fig, "fill_between");
}

void plotBrokenBarH(GalleryCtx& ctx) {
    Figure fig(1, 1);
    auto* ax = setupAxes(fig, "Broken Bar Horizontal");
    ax->style().xAxis.label = "X";
    ax->style().yAxis.label = "Y";
    std::vector<BarHSegment> segs = {
        {0, 5, 0, 1},
        {7, 3, 0, 1},
        {2, 4, 2, 1},
        {8, 2, 2, 1},
    };
    BrokenBarHConfig cfg;
    cfg.colors = {
        Color::fromRgba8(31, 119, 180, 200),
        Color::fromRgba8(255, 127, 14, 200),
        Color::fromRgba8(44, 160, 44, 200),
        Color::fromRgba8(214, 39, 40, 200),
    };
    ax->addPlot(std::make_unique<BrokenBarHPlot>(std::move(segs), cfg));
    ctx.render(fig, "broken_barh");
}

void plotHeatmap(GalleryCtx& ctx) {
    Figure fig(1, 1);
    auto* ax = setupAxes(fig, "Heatmap");
    Grid2D grid;
    grid.width = 30;
    grid.height = 20;
    grid.xRange = {0, 10};
    grid.yRange = {0, 10};
    grid.values.resize(30 * 20);
    for (uint32_t j = 0; j < 20; ++j)
        for (uint32_t i = 0; i < 30; ++i) {
            float x = float(i) / 29 * 10;
            float y = float(j) / 19 * 10;
            grid.values[j * 30 + i] = std::sin(x * 0.5f) * std::cos(y * 0.5f);
        }
    ax->addPlot(std::make_unique<HeatmapPlot>(std::move(grid)));
    ax->style().colorbar.visible = true;
    ax->style().colorbar.colormap = "viridis";
    ctx.render(fig, "heatmap");
}

void plotHist2D(GalleryCtx& ctx) {
    Figure fig(1, 1);
    auto* ax = setupAxes(fig, "2D Histogram");
    std::normal_distribution<float> d(0, 2);
    std::vector<float> x, y;
    for (int i = 0; i < 5000; ++i) {
        x.push_back(d(rng()));
        y.push_back(d(rng()));
    }
    Hist2DConfig cfg;
    cfg.nBinsX = 40;
    cfg.nBinsY = 30;
    ax->addPlot(std::make_unique<Hist2DPlot>(x, y, cfg));
    ax->style().colorbar.visible = true;
    ctx.render(fig, "hist2d");
}

void plotHexbin(GalleryCtx& ctx) {
    Figure fig(1, 1);
    auto* ax = setupAxes(fig, "Hexbin");
    std::normal_distribution<float> d(0, 2);
    std::vector<float> x, y;
    for (int i = 0; i < 3000; ++i) {
        x.push_back(d(rng()));
        y.push_back(d(rng()));
    }
    HexbinConfig cfg;
    cfg.gridsize = 25;
    ax->addPlot(std::make_unique<HexbinPlot>(x, y, cfg));
    ax->style().colorbar.visible = true;
    ctx.render(fig, "hexbin");
}

void plotContour(GalleryCtx& ctx) {
    Figure fig(1, 1);
    auto* ax = setupAxes(fig, "Contour");
    Grid2D grid;
    grid.width = 50;
    grid.height = 50;
    grid.xRange = {-3, 3};
    grid.yRange = {-3, 3};
    grid.values.resize(50 * 50);
    for (uint32_t j = 0; j < 50; ++j)
        for (uint32_t i = 0; i < 50; ++i) {
            float x = -3 + float(i) / 49 * 6;
            float y = -3 + float(j) / 49 * 6;
            grid.values[j * 50 + i] = std::sin(x) * std::cos(y);
        }
    ContourConfig cfg;
    ax->addPlot(std::make_unique<ContourPlot>(std::move(grid), cfg));
    ctx.render(fig, "contour");
}

void plotContourf(GalleryCtx& ctx) {
    Figure fig(1, 1);
    auto* ax = setupAxes(fig, "Filled Contour");
    Grid2D grid;
    grid.width = 50;
    grid.height = 50;
    grid.xRange = {-3, 3};
    grid.yRange = {-3, 3};
    grid.values.resize(50 * 50);
    for (uint32_t j = 0; j < 50; ++j)
        for (uint32_t i = 0; i < 50; ++i) {
            float x = -3 + float(i) / 49 * 6;
            float y = -3 + float(j) / 49 * 6;
            grid.values[j * 50 + i] = -(x*x + y*y);
        }
    ContourConfig cfg;
    ax->addPlot(std::make_unique<ContourfPlot>(std::move(grid), cfg));
    ax->style().colorbar.visible = true;
    ctx.render(fig, "contourf");
}

void plotKDE(GalleryCtx& ctx) {
    Figure fig(1, 1);
    auto* ax = setupAxes(fig, "KDE");
    std::normal_distribution<float> d(0, 1);
    std::vector<Point2D> samples;
    for (int i = 0; i < 500; ++i)
        samples.push_back({d(rng()), d(rng())});
    ax->addPlot(std::make_unique<KDEPlot>(std::move(samples)));
    ax->style().colorbar.visible = true;
    ctx.render(fig, "kde");
}

void plotECDF(GalleryCtx& ctx) {
    Figure fig(1, 1);
    auto* ax = setupAxes(fig, "ECDF");
    ax->style().xAxis.label = "Value";
    ax->style().yAxis.label = "CDF";
    std::normal_distribution<float> d(0, 1);
    std::vector<float> samples;
    for (int i = 0; i < 500; ++i)
        samples.push_back(d(rng()));
    ECDFConfig cfg;
    cfg.fill = true;
    ax->addPlot(std::make_unique<ECDFPlot>(std::move(samples), cfg));
    ctx.render(fig, "ecdf");
}

void plotSurface(GalleryCtx& ctx) {
    Figure fig(1, 1);
    auto* ax = setupAxes(fig, "3D Surface");
    Grid2D grid;
    grid.width = 40;
    grid.height = 40;
    grid.xRange = {-5, 5};
    grid.yRange = {-5, 5};
    grid.values.resize(40 * 40);
    for (uint32_t j = 0; j < 40; ++j)
        for (uint32_t i = 0; i < 40; ++i) {
            float x = -5 + float(i) / 39 * 10;
            float y = -5 + float(j) / 39 * 10;
            grid.values[j * 40 + i] = std::sin(x * 0.5f) * std::cos(y * 0.5f);
        }
    Camera3D cam{{8, 8, 8}, {0, 0, 0}, {0, 0, 1}};
    cam.aspect = float(kWidth) / float(kHeight);
    auto p = std::make_unique<SurfacePlot>(std::move(grid), cam);
    ax->addPlot(std::move(p));
    ctx.render(fig, "surface");
}

void plotWireframe(GalleryCtx& ctx) {
    Figure fig(1, 1);
    auto* ax = setupAxes(fig, "3D Wireframe");
    Grid2D grid;
    grid.width = 20;
    grid.height = 20;
    grid.xRange = {-5, 5};
    grid.yRange = {-5, 5};
    grid.values.resize(20 * 20);
    for (uint32_t j = 0; j < 20; ++j)
        for (uint32_t i = 0; i < 20; ++i) {
            float x = -5 + float(i) / 19 * 10;
            float y = -5 + float(j) / 19 * 10;
            grid.values[j * 20 + i] = std::sin(x * 0.5f) * std::cos(y * 0.5f);
        }
    Camera3D cam{{8, 8, 8}, {0, 0, 0}, {0, 0, 1}};
    cam.aspect = float(kWidth) / float(kHeight);
    WireframeConfig cfg;
    auto p = std::make_unique<WireframePlot>(std::move(grid), cfg);
    p->setCamera(cam);
    ax->addPlot(std::move(p));
    ctx.render(fig, "wireframe");
}

void plotScatter3D(GalleryCtx& ctx) {
    Figure fig(1, 1);
    auto* ax = setupAxes(fig, "3D Scatter");
    std::normal_distribution<float> d(0, 1);
    std::vector<float> x, y, z;
    for (int i = 0; i < 100; ++i) {
        x.push_back(d(rng()) * 3);
        y.push_back(d(rng()) * 3);
        z.push_back(d(rng()) * 3);
    }
    Camera3D cam{{8, 8, 8}, {0, 0, 0}, {0, 0, 1}};
    cam.aspect = float(kWidth) / float(kHeight);
    Scatter3DConfig cfg;
    auto p = std::make_unique<Scatter3D>(x, y, z, cfg);
    p->setCamera(cam);
    ax->addPlot(std::move(p));
    ctx.render(fig, "scatter3d");
}

void plotPlot3D(GalleryCtx& ctx) {
    Figure fig(1, 1);
    auto* ax = setupAxes(fig, "3D Line");
    std::vector<float> x, y, z;
    for (int i = 0; i < 200; ++i) {
        float t = float(i) / 199 * 4 * M_PI;
        x.push_back(std::cos(t) * 3);
        y.push_back(std::sin(t) * 3);
        z.push_back(t * 0.5f);
    }
    Camera3D cam{{10, 10, 10}, {0, 0, 3}, {0, 0, 1}};
    cam.aspect = float(kWidth) / float(kHeight);
    Plot3DConfig cfg;
    auto p = std::make_unique<Plot3D>(x, y, z, cfg);
    p->setCamera(cam);
    ax->addPlot(std::move(p));
    ctx.render(fig, "plot3d");
}

void plotBar3D(GalleryCtx& ctx) {
    Figure fig(1, 1);
    auto* ax = setupAxes(fig, "3D Bar");
    std::vector<float> bx, by, bz, dx, dy, dz;
    for (int i = 0; i < 4; ++i)
        for (int j = 0; j < 4; ++j) {
            bx.push_back(float(i));
            by.push_back(float(j));
            bz.push_back(0);
            dx.push_back(0.7f);
            dy.push_back(0.7f);
            dz.push_back(float(i + j + 1));
        }
    Camera3D cam{{10, 10, 10}, {1.5f, 1.5f, 2}, {0, 0, 1}};
    cam.aspect = float(kWidth) / float(kHeight);
    auto p = std::make_unique<Bar3D>(bx, by, bz, dx, dy, dz);
    p->setCamera(cam);
    ax->addPlot(std::move(p));
    ctx.render(fig, "bar3d");
}

void plotMexicanHat(GalleryCtx& ctx) {
    Figure fig(1, 1);
    auto* ax = setupAxes(fig, "Mexican Hat Wavelet");
    Camera3D cam{{8, 8, 8}, {0, 0, 0}, {0, 0, 1}};
    cam.aspect = float(kWidth) / float(kHeight);
    MexicanHatConfig cfg;
    auto p = std::make_unique<MexicanHatPlot>(1.0f, Range{-5, 5}, Range{-5, 5}, 40, 40, cfg);
    p->setCamera(cam);
    ax->addPlot(std::move(p));
    ctx.render(fig, "mexican_hat");
}

void plotChirp(GalleryCtx& ctx) {
    Figure fig(1, 1);
    auto* ax = setupAxes(fig, "Chirp Signal");
    ax->style().xAxis.label = "Time";
    ax->style().yAxis.label = "Amplitude";
    ChirpPlotConfig cfg;
    cfg.color = Color::fromRgba8(31, 119, 180);
    cfg.lineWidth = 1.5f;
    ax->addPlot(std::make_unique<ChirpPlot>(1.0, 50.0, 1.0, Range{0, 1}, 2000, cfg));
    ctx.render(fig, "chirp");
}

} // namespace

int main(int argc, char** argv) {
    std::string outDir = "gallery/volcano";
    if (argc > 1) outDir = argv[1];

    std::cout << "Generating VolcanoPlot gallery in " << outDir << "/\n";
    GalleryCtx ctx(outDir);

    // 2D plots
    plotScatter(ctx);
    plotLine(ctx);
    plotBar(ctx);
    plotGroupedBar(ctx);
    plotHist(ctx);
    plotPie(ctx);
    plotBox(ctx);
    plotViolin(ctx);
    plotStack(ctx);
    plotStem(ctx);
    plotStep(ctx);
    plotErrorbar(ctx);
    plotFill(ctx);
    plotFillBetween(ctx);
    plotBrokenBarH(ctx);
    plotHeatmap(ctx);
    plotHist2D(ctx);
    plotHexbin(ctx);
    plotContour(ctx);
    plotContourf(ctx);
    plotKDE(ctx);
    plotECDF(ctx);

    // 3D plots
    plotSurface(ctx);
    plotWireframe(ctx);
    plotScatter3D(ctx);
    plotPlot3D(ctx);
    plotBar3D(ctx);
    plotMexicanHat(ctx);
    plotChirp(ctx);

    std::cout << "Done. Generated " << 29 << " plots.\n";
    return 0;
}
